exp_name: DIFFUSION_AQGT_HAND_1

gpu_num: 0
num_gpu: 1
subject: Hand
dataset_name: aqgt

data_path: data/
dataset: aqgt/
train_data_path: train
val_data_path: val
test_data_path: test
out_dir: output

embed_evaluator_path: gesture_autoencoder_checkpoint_best.bin
vqvae_path: output/VQVAE_AQGT/VQVAE_AQGT_21_bestFGD.bin

# train params
epochs: 500
batch_size: 32
lr: 2e-4
lr_scheduler: [50, 100, 150, 200, 250, 300, 350, 400, 450]
gamma: 0.5
recons_loss: l2
eval_iter: 1
weight_decay: 0
loader_workers: 4
monitor: FGD
save_top_k: 2
mode: min

#diffusion
nb_steps: 100
beta_schedule: linear




